# Development override - use with: docker-compose -f docker-compose.yml -f docker-compose.override.yml up
version: '3.8'

services:
  idle-clans-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development
      - .:/app
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5001:5000"  # Different port for dev
    command: ["python", "main_web.py"]